package com.finvest.config;

import com.finvest.entity.Fund;
import com.finvest.entity.User;
import com.finvest.entity.User.Role;
import com.finvest.repository.FundRepository;
import com.finvest.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;

@Component
public class DataSeeder implements CommandLineRunner {

    private static final Logger log = Logger.getLogger(DataSeeder.class.getName());

    @Autowired private UserRepository userRepo;
    @Autowired private FundRepository fundRepo;
    @Autowired private PasswordEncoder encoder;

    @Override
    public void run(String... args) {
        seedUsers();
        seedFunds();
    }

    private void seedUsers() {
        seedUser("Abhiram Kotamarthy", "abhiramkotamarthisubrahmanya@gmail.com", "Abhi@321", Role.admin);
        seedUser("Advisor Sharma",     "advisor@example.com",  "pass", Role.advisor);
        seedUser("Analyst Gupta",      "analyst@example.com",  "pass", Role.analyst);
    }

    private void seedUser(String name, String email, String raw, Role role) {
        if (!userRepo.existsByEmail(email)) {
            userRepo.save(new User(name, email, encoder.encode(raw), role));
            log.info("Seeded: " + email);
        }
    }

    private Fund f(String id, String name, String amc, String cat, String sub,
                   double nav, double aum, double er, double erd,
                   int sip, String risk,
                   double r1, double r3, double r5, double ri,
                   String inc, String exit, String b1, String b2,
                   String about, String ideal, String obj,
                   String mn, String md, String ma) {
        Fund x = new Fund();
        x.setId(id); x.setName(name); x.setAmc(amc);
        x.setCategory(cat); x.setSubCategory(sub);
        x.setNav(nav); x.setAum(aum);
        x.setExpenseRatioRegular(er); x.setExpenseRatioDirect(erd);
        x.setMinSip(sip); x.setRisk(risk);
        x.setReturn1y(r1); x.setReturn3y(r3); x.setReturn5y(r5); x.setReturnSinceInception(ri);
        x.setInceptionDate(inc); x.setExitLoad(exit);
        x.setBenchmarkTier1(b1); x.setBenchmarkTier2(b2);
        x.setAbout(about); x.setIdealFor(ideal); x.setInvestmentObjective(obj);
        x.setFundManagerName(mn); x.setFundManagerDesignation(md); x.setFundManagerAbout(ma);
        return x;
    }

    private void seedFunds() {
        // Seed each fund individually by ID — safe to re-run, only inserts missing ones
        List<Fund> funds = new ArrayList<>();

        // ── LARGE CAP (10) ────────────────────────────────────────────────────
        funds.add(f("SBIN_BC","SBI Bluechip Fund - Direct Growth","SBI Mutual Fund","Equity","Large Cap",90.47,45623,0.96,0.46,500,"Moderate",16.2,18.4,17.6,14.8,"14-Feb-2006","1% within 1 year","Nifty 100 TRI","S&P BSE 100 TRI","One of India's most trusted large-cap equity funds.","Investors seeking stable long-term wealth creation.","Long-term growth through large-cap stocks.","Sohini Andani","Fund Manager","20+ years equity research experience."));
        funds.add(f("HDFC_TOP100","HDFC Top 100 Fund - Direct Growth","HDFC Mutual Fund","Equity","Large Cap",1021.34,35248,1.60,0.80,100,"Moderate",15.8,20.1,18.2,16.4,"11-Oct-1996","1% within 1 year","Nifty 100 TRI","Nifty 50 TRI","India's oldest large-cap fund since 1996.","Conservative equity investors.","Capital appreciation through top 100 stocks.","Rahul Baijal","Senior Fund Manager","25+ years at HDFC AMC."));
        funds.add(f("AXIS_BFC","Axis Bluechip Fund - Direct Growth","Axis Mutual Fund","Equity","Large Cap",62.84,32145,1.58,0.44,500,"Moderate",14.6,16.8,17.9,15.2,"05-Jan-2010","1% within 1 year","Nifty 100 TRI","Nifty 50 TRI","Quality-focused large-cap fund with 25-30 stocks.","Investors preferring quality-focused approach.","Long-term appreciation in large-cap quality stocks.","Shreyash Devalkar","Senior Fund Manager","Managing Rs.32000+ Cr."));
        funds.add(f("ICICI_LC","ICICI Pru Bluechip Fund - Direct Growth","ICICI Prudential MF","Equity","Large Cap",98.21,47823,1.07,0.48,100,"Moderate",15.1,19.8,17.4,15.9,"23-May-2008","1% within 1 year","Nifty 100 TRI","Nifty 50 TRI","Large-cap fund investing in India's top 100 companies.","Long-term investors wanting low-volatility equity exposure.","Consistent returns through large-cap blue-chip stocks.","Anish Tawakley","Deputy CIO","20+ years managing large-cap equity portfolios."));
        funds.add(f("KOTAK_BC","Kotak Bluechip Fund - Direct Growth","Kotak Mahindra MF","Equity","Large Cap",572.34,8234,1.68,0.56,100,"Moderate",13.8,18.2,16.7,14.2,"29-Dec-1998","1% within 1 year","Nifty 100 TRI","Nifty 50 TRI","Veteran large-cap fund with 25+ year track record.","Conservative equity investors with 3-5 year horizon.","Capital appreciation through diversified large-cap portfolio.","Harsha Upadhyaya","CIO - Equity","20+ years experience in equity fund management."));
        funds.add(f("MIRAE_LC","Mirae Asset Large Cap Fund - Direct","Mirae Asset MF","Equity","Large Cap",98.41,38921,0.54,0.54,1000,"Moderate",14.9,19.4,18.1,17.3,"04-Apr-2008","1% within 1 year","Nifty 100 TRI","S&P BSE 100 TRI","Consistent large-cap outperformer backed by Korean AMC research.","Investors with 3+ year horizon seeking market-linked returns.","Long-term capital appreciation through high-quality large-cap stocks.","Gaurav Kochar","Fund Manager","IIT/IIM alumnus with 15+ years fund management experience."));
        funds.add(f("DSP_TOP100","DSP Top 100 Equity Fund - Direct","DSP Mutual Fund","Equity","Large Cap",374.52,3921,1.76,0.79,500,"Moderate",14.2,17.9,16.1,14.8,"10-Mar-2003","1% within 1 year","Nifty 100 TRI","Nifty 50 TRI","Concentrates on top 100 companies by market cap.","Investors wanting to participate in India's blue-chip growth story.","Long-term wealth creation through top 100 Indian companies.","Rohit Singhania","Fund Manager","18+ years of equity research and fund management."));
        funds.add(f("CANARA_BC","Canara Robeco Bluechip Equity - Direct","Canara Robeco MF","Equity","Large Cap",59.83,11234,0.40,0.40,1000,"Moderate",16.3,20.1,18.4,14.1,"20-Aug-2010","1% within 1 year","Nifty 100 TRI","Nifty 50 TRI","Consistently one of the top-ranked large-cap funds in India.","Investors seeking benchmark-beating returns with low volatility.","Long-term capital growth through fundamentally strong large-cap companies.","Shridatta Bhandwaldar","Head of Equities","Quantitative approach to stock selection with 20+ years experience."));
        funds.add(f("NIPPON_LC","Nippon India Large Cap Fund - Direct","Nippon India MF","Equity","Large Cap",82.34,19234,0.83,0.83,100,"Moderate",13.4,16.8,15.2,13.7,"08-Aug-2007","1% within 1 year","Nifty 100 TRI","Nifty 50 TRI","One of Nippon India's flagship large-cap offerings.","Investors looking for index-plus returns in large-cap space.","Capital appreciation through investment in top 100 companies.","Sailesh Bhan","Deputy CIO","22+ years in equity markets."));
        funds.add(f("FRANKLIN_BC","Franklin India Bluechip Fund - Direct","Franklin Templeton MF","Equity","Large Cap",978.21,6234,1.16,0.66,500,"Moderate",12.8,16.1,14.9,18.2,"01-Dec-1993","1% within 1 year","Nifty 100 TRI","Nifty 50 TRI","India's first-ever equity mutual fund, launched 1993.","Long-term conservative equity investors.","Steady wealth creation through India's largest companies.","R. Janakiraman","VP & Portfolio Manager","25+ years in Indian equity markets."));

        // ── MID CAP (10) ──────────────────────────────────────────────────────
        funds.add(f("SUND_MC","Sundaram Midcap Fund - Direct","Sundaram Mutual Fund","Equity","Mid Cap",1425.39,13293,1.73,0.86,100,"High",11.53,27.44,28.24,22.34,"01-Jul-2002","1% within 1 year","Nifty MidCap 150 TRI","Nifty Mid Cap 100 TRI","22-year track record in mid-cap investing.","Aggressive investors with 5-7 year horizon.","Long-term appreciation through mid-cap stocks.","Bharath S","Head - Equities","Head Equities at Sundaram AMC."));
        funds.add(f("AXIS_MC","Axis Midcap Fund - Direct","Axis Mutual Fund","Equity","Mid Cap",102.34,23456,1.64,0.43,500,"High",18.6,22.8,24.3,20.1,"18-Feb-2011","1% within 1 year","Nifty Midcap 150 TRI","Nifty Midcap 100 TRI","Quality mid-cap fund with strong long-term track record.","5+ year investors seeking alpha.","Long-term capital growth through quality mid-cap companies.","Shreyash Devalkar","Senior Fund Manager","Rs.23000+ Cr under management."));
        funds.add(f("KOTAK_EMC","Kotak Emerging Equity - Direct","Kotak Mahindra MF","Equity","Mid Cap",118.75,41263,1.52,0.38,100,"High",22.4,26.1,27.8,18.9,"30-Mar-2007","1% within 1 year","Nifty Midcap 150 TRI","Nifty Midcap 100 TRI","India's largest mid-cap fund by AUM.","Investors wanting high-growth mid-cap exposure.","Capital appreciation through emerging mid-cap companies.","Pankaj Tibrewal","Senior EVP and Fund Manager","20+ years in mid-cap equity."));
        funds.add(f("HDFC_MIDCAP","HDFC Mid-Cap Opportunities - Direct","HDFC Mutual Fund","Equity","Mid Cap",142.87,69234,0.96,0.46,100,"High",21.8,28.4,26.7,21.4,"25-Jun-2007","1% within 1 year","Nifty Midcap 150 TRI","Nifty Midcap 100 TRI","India's second-largest mid-cap fund with exceptional track record.","Investors with 5+ year view seeking mid-cap alpha.","Long-term wealth creation through fundamentally strong mid-cap stocks.","Chirag Setalvad","Senior Fund Manager","22+ years of equity market experience."));
        funds.add(f("DSP_MIDCAP","DSP Midcap Fund - Direct","DSP Mutual Fund","Equity","Mid Cap",111.23,18923,0.83,0.83,500,"High",19.4,23.6,25.1,19.8,"14-Nov-2006","1% within 1 year","Nifty Midcap 150 TRI","Nifty Midcap 100 TRI","Disciplined mid-cap fund with robust risk management.","Investors seeking growth through mid-cap exposure.","Capital appreciation through quality mid-cap businesses.","Vinit Sambre","Head of Equities","17+ years in equity fund management."));
        funds.add(f("NIPPON_GRO","Nippon India Growth Fund - Direct","Nippon India MF","Equity","Mid Cap",3847.21,26712,0.98,0.98,100,"High",20.1,24.8,23.4,22.1,"05-Oct-1995","1% within 1 year","Nifty Midcap 150 TRI","Nifty Midcap 100 TRI","India's oldest mid-cap fund, running since 1995.","Long-term mid-cap investors with 5+ year view.","Long-term capital appreciation through quality mid-cap companies.","Manish Gunwani","CIO - Equity","25+ years in equity markets."));
        funds.add(f("EDELWEISS_MC","Edelweiss Mid Cap Fund - Direct","Edelweiss MF","Equity","Mid Cap",82.34,7234,0.52,0.52,500,"High",23.8,28.7,27.2,18.4,"26-Dec-2007","1% within 1 year","Nifty Midcap 150 TRI","Nifty Midcap 100 TRI","Data-driven mid-cap fund with factor-based approach.","Investors seeking systematic mid-cap wealth creation.","Capital appreciation through a systematic, data-driven mid-cap approach.","Trideep Bhattacharya","CIO - Equities","20+ years in equity fund management."));
        funds.add(f("FRANKLIN_MC","Franklin India Prima Fund - Direct","Franklin Templeton MF","Equity","Mid Cap",2234.12,7823,1.41,0.91,500,"High",17.9,21.3,22.8,20.4,"01-Dec-1993","1% within 1 year","Nifty Midcap 150 TRI","Nifty Midcap 100 TRI","India's oldest mid-cap fund from Franklin, launched 1993.","Long-term mid-cap investors.","Wealth creation through mid-cap and small-cap stocks.","Hari Shyamsunder","Fund Manager","18+ years in equity markets."));
        funds.add(f("MOTILAL_MC","Motilal Oswal Midcap Fund - Direct","Motilal Oswal MF","Equity","Mid Cap",92.34,18234,0.66,0.66,500,"High",35.6,31.2,29.8,24.3,"24-Feb-2014","1% within 1 year","Nifty Midcap 150 TRI","Nifty Midcap 100 TRI","High-conviction concentrated mid-cap portfolio (25-30 stocks).","Investors seeking focused alpha-generating mid-cap fund.","Long-term wealth creation through concentrated quality mid-cap bets.","Niket Shah","Fund Manager","16+ years of equity research experience."));
        funds.add(f("PGIM_MC","PGIM India Midcap Opp Fund - Direct","PGIM India MF","Equity","Mid Cap",63.21,8123,0.50,0.50,1000,"High",26.4,30.1,28.9,20.7,"02-Dec-2013","1% within 1 year","Nifty Midcap 150 TRI","Nifty Midcap 100 TRI","Global mid-cap expertise with Indian market focus.","Investors seeking global-quality mid-cap exposure.","Long-term capital growth through quality mid-cap companies.","Aniruddha Naha","Head of Equities","18+ years fund management experience."));

        // ── SMALL CAP (8) ─────────────────────────────────────────────────────
        funds.add(f("SBI_SC","SBI Small Cap Fund - Direct","SBI Mutual Fund","Equity","Small Cap",182.34,26783,1.71,0.68,500,"Very High",24.8,31.2,35.4,23.1,"09-Sep-2009","1% within 1 year","S&P BSE 250 SmallCap TRI","Nifty Smallcap 250 TRI","India's best-performing small-cap fund.","High-risk investors with 7+ year horizon.","Capital appreciation through high-growth small-cap companies.","R. Srinivasan","CIO - Equity","20+ years in small-cap investing."));
        funds.add(f("NIPPON_SC","Nippon India Small Cap - Direct","Nippon India MF","Equity","Small Cap",165.82,52140,1.56,0.68,100,"Very High",28.4,36.8,38.2,22.4,"16-Sep-2010","1% within 1 year","Nifty Smallcap 250 TRI","S&P BSE 250 SmallCap TRI","India's largest small-cap fund managing Rs.52000+ Cr.","Aggressive investors with 7-10 year horizon.","Long-term capital appreciation through small-cap stocks.","Samir Rachh","Fund Manager","15+ years small-cap expertise."));
        funds.add(f("AXIS_SC","Axis Small Cap Fund - Direct","Axis Mutual Fund","Equity","Small Cap",98.23,23421,0.61,0.61,500,"Very High",31.2,35.8,36.1,24.7,"29-Nov-2013","1% within 1 year","S&P BSE 250 SmallCap TRI","Nifty Smallcap 250 TRI","Quality-focused small-cap fund with exceptional risk-adjusted returns.","Long-term investors seeking small-cap wealth creation.","Capital appreciation through fundamentally strong small-cap companies.","Anupam Tiwari","Fund Manager","15+ years equity experience."));
        funds.add(f("HDFC_SC","HDFC Small Cap Fund - Direct","HDFC Mutual Fund","Equity","Small Cap",128.34,32421,0.68,0.68,500,"Very High",22.8,28.9,32.4,19.8,"03-Apr-2008","1% within 1 year","Nifty Smallcap 250 TRI","S&P BSE 250 SmallCap TRI","Disciplined small-cap fund with quality-at-right-price approach.","Investors with high risk tolerance and 7+ year view.","Long-term wealth creation through small-cap quality businesses.","Chirag Setalvad","Senior Fund Manager","22+ years equity experience."));
        funds.add(f("KOTAK_SC","Kotak Small Cap Fund - Direct","Kotak Mahindra MF","Equity","Small Cap",256.78,16234,0.59,0.59,500,"Very High",26.9,33.4,34.8,21.3,"24-Feb-2005","1% within 1 year","Nifty Smallcap 250 TRI","S&P BSE 250 SmallCap TRI","Bottom-up small-cap fund with strong stock-picking track record.","High-risk investors with 5-7 year investment horizon.","Capital appreciation through bottom-up small-cap stock selection.","Pankaj Tibrewal","Senior EVP","20+ years in small and mid-cap equity."));
        funds.add(f("DSP_SC","DSP Small Cap Fund - Direct","DSP Mutual Fund","Equity","Small Cap",182.12,11923,0.83,0.83,500,"Very High",29.4,37.2,38.6,23.8,"14-Jun-2007","1% within 1 year","Nifty Smallcap 250 TRI","S&P BSE 250 SmallCap TRI","Consistent alpha generator in small-cap space.","Aggressive long-term investors.","Long-term capital appreciation through small-cap companies.","Vinit Sambre","Head of Equities","17+ years equity management."));
        funds.add(f("ICICI_SC","ICICI Pru Smallcap Fund - Direct","ICICI Prudential MF","Equity","Small Cap",87.34,7234,0.79,0.79,500,"Very High",31.8,36.1,37.2,22.1,"18-Oct-2007","1% within 1 year","Nifty Smallcap 250 TRI","S&P BSE 250 SmallCap TRI","ICICI's small-cap fund with proprietary research backing.","Investors seeking aggressive returns from small-cap.","Long-term wealth creation through small-cap companies.","Harish Bihani","Fund Manager","16+ years equity experience."));
        funds.add(f("FRANKLIN_SC","Franklin India Smaller Companies - Direct","Franklin Templeton MF","Equity","Small Cap",142.56,7821,1.36,0.86,500,"Very High",19.8,24.3,27.6,19.4,"13-Jan-2006","1% within 1 year","Nifty Smallcap 250 TRI","S&P BSE 250 SmallCap TRI","Veteran small-cap fund with 18+ year history.","High-risk long-term investors.","Capital appreciation through smaller companies with growth potential.","R. Janakiraman","VP and Portfolio Manager","25+ years equity experience."));

        // ── FLEXI CAP (6) ─────────────────────────────────────────────────────
        funds.add(f("PPFAS_FC","Parag Parikh Flexi Cap - Direct","PPFAS Mutual Fund","Equity","Flexi Cap",83.47,68234,1.41,0.63,1000,"High",21.4,25.6,26.8,20.9,"28-May-2013","2% within 1 year, 1% within 2 years","Nifty 500 Multicap 50:25:25 TRI","S&P BSE 500 TRI","India's most trusted flexi-cap with global equity exposure.","Long-term value investors comfortable with global diversification.","Long-term capital growth through domestic and international equity.","Rajeev Thakkar","CIO","Buffett-style value investing approach."));
        funds.add(f("HDFC_FC","HDFC Flexi Cap Fund - Direct","HDFC Mutual Fund","Equity","Flexi Cap",1574.23,54612,1.56,0.77,100,"High",17.8,26.5,22.1,21.9,"01-Jan-1995","1% within 1 year","Nifty 500 TRI","S&P BSE 500 TRI","India's oldest equity fund since 1995.","Long-term investors seeking benchmark-beating returns.","Capital appreciation across large, mid and small cap stocks.","Roshi Jain","Fund Manager","25+ years experience."));
        funds.add(f("CANARA_FLEXI","Canara Robeco Flexi Cap - Direct","Canara Robeco MF","Equity","Flexi Cap",289.34,11234,0.43,0.43,1000,"High",18.9,22.4,21.7,17.8,"02-Sep-2003","1% within 1 year","Nifty 500 TRI","S&P BSE 500 TRI","Consistent outperformer with disciplined stock selection.","Long-term investors seeking multi-cap alpha.","Capital appreciation through dynamic allocation across market caps.","Shridatta Bhandwaldar","Head of Equities","20+ years quantitative fund management."));
        funds.add(f("UTI_FC","UTI Flexi Cap Fund - Direct","UTI Mutual Fund","Equity","Flexi Cap",298.34,24921,1.02,0.52,500,"High",16.4,20.8,19.3,17.4,"18-May-1992","1% within 1 year","Nifty 500 TRI","S&P BSE 500 TRI","One of India's oldest flexi-cap funds, since 1992.","Long-term investors with 5+ year horizon.","Long-term capital appreciation through diversified portfolio.","Ajay Tyagi","Fund Manager","20+ years equity experience."));
        funds.add(f("FRANKLIN_FC","Franklin India Flexi Cap - Direct","Franklin Templeton MF","Equity","Flexi Cap",1423.21,12921,1.01,0.51,500,"High",14.8,18.6,17.9,18.4,"29-Sep-1994","1% within 1 year","Nifty 500 TRI","S&P BSE 500 TRI","30-year track record in flexi-cap investing.","Long-term wealth seekers across market caps.","Wealth creation through a mix of large, mid and small cap stocks.","R. Janakiraman","VP and Portfolio Manager","25+ years equity experience."));
        funds.add(f("INVESCO_FC","Invesco India Flexi Cap - Direct","Invesco India MF","Equity","Flexi Cap",98.23,8234,0.65,0.65,500,"High",19.8,23.4,22.1,18.3,"07-Oct-2020","1% within 1 year","Nifty 500 TRI","S&P BSE 500 TRI","Newer flexi-cap fund with strong team and process.","Investors seeking actively managed multi-cap exposure.","Long-term capital growth through disciplined cross-cap allocation.","Amit Ganatra","Head of Equities","20+ years equity experience."));

        // ── ELSS (6) ──────────────────────────────────────────────────────────
        funds.add(f("AXIS_ELSS","Axis Long Term Equity - Direct","Axis Mutual Fund","Equity","ELSS",90.12,34521,1.63,0.53,500,"High",15.2,18.4,19.8,17.6,"29-Dec-2009","Nil (3-year lock-in)","Nifty 500 TRI","S&P BSE 500 TRI","India's most popular ELSS fund.","Salaried investors saving tax under 80C.","Long-term appreciation plus tax benefit under Section 80C.","Jinesh Gopani","Head of Equity","Pioneer of ELSS category in India."));
        funds.add(f("MIRAE_ELSS","Mirae Asset Tax Saver - Direct","Mirae Asset MF","Equity","ELSS",41.23,22341,0.29,0.29,500,"High",17.8,22.1,21.4,19.2,"28-Dec-2015","Nil (3-year lock-in)","Nifty 200 TRI","S&P BSE 200 TRI","Lowest-cost ELSS fund with consistent top-quartile performance.","Tax-saving investors wanting maximum returns with minimum cost.","Tax-efficient long-term wealth creation with 80C benefit.","Neelesh Surana","CIO","20+ years in equity fund management."));
        funds.add(f("HDFC_ELSS","HDFC TaxSaver Fund - Direct","HDFC Mutual Fund","Equity","ELSS",1023.12,12923,1.73,1.03,500,"High",14.2,17.8,16.9,24.1,"31-Mar-1996","Nil (3-year lock-in)","Nifty 500 TRI","S&P BSE 500 TRI","India's oldest ELSS fund running since 1996.","Long-term tax-savers wanting dividend or growth option.","Tax-saving with long-term capital appreciation.","Roshi Jain","Fund Manager","25+ years in equity markets."));
        funds.add(f("ICICI_ELSS","ICICI Pru Long Term Equity - Direct","ICICI Prudential MF","Equity","ELSS",812.34,13421,1.82,1.12,500,"High",13.8,16.9,16.2,18.8,"19-Aug-1999","Nil (3-year lock-in)","Nifty 500 TRI","S&P BSE 500 TRI","Disciplined ELSS fund with strong large-cap bias.","Conservative tax-savers wanting stable equity returns.","Tax saving with consistent long-term equity wealth creation.","George Heber Joseph","CEO and CIO","25+ years in Indian equity markets."));
        funds.add(f("DSP_ELSS","DSP Tax Saver Fund - Direct","DSP Mutual Fund","Equity","ELSS",102.34,14234,0.79,0.79,500,"High",16.4,20.1,19.8,16.7,"18-Jan-2007","Nil (3-year lock-in)","Nifty 500 TRI","S&P BSE 500 TRI","Diversified ELSS with multi-cap approach.","Tax-saving investors preferring diversified exposure.","Tax benefit with long-term multi-cap capital appreciation.","Rohit Singhania","Fund Manager","18+ years fund management experience."));
        funds.add(f("KOTAK_ELSS","Kotak ELSS Tax Saver - Direct","Kotak Mahindra MF","Equity","ELSS",112.34,8123,0.59,0.59,500,"High",14.9,18.4,17.8,16.2,"26-Nov-2005","Nil (3-year lock-in)","Nifty 500 TRI","S&P BSE 500 TRI","Consistent ELSS outperformer with value tilt.","Tax-savers wanting value-oriented approach.","Tax saving with value-based equity wealth creation.","Harsha Upadhyaya","CIO - Equity","20+ years equity experience."));

        // ── HYBRID (8) ────────────────────────────────────────────────────────
        funds.add(f("ICICI_BAF","ICICI Pru Balanced Advantage - Direct","ICICI Prudential MF","Hybrid","Balanced Advantage",64.82,56789,1.68,0.92,500,"Moderate",12.4,16.2,14.9,13.6,"30-Dec-2006","1% within 1 year","CRISIL Hybrid 50+50 Index","Nifty 50 Hybrid 50:50 Index","Dynamic allocation fund adjusting equity/debt based on market P/E.","First-time investors and conservative equity investors.","Dynamic equity-debt allocation for consistent risk-adjusted returns.","Sankaran Naren","CIO","India's most respected fund manager."));
        funds.add(f("HDFC_HYBRID","HDFC Balanced Advantage - Direct","HDFC Mutual Fund","Hybrid","Balanced Advantage",472.18,87654,1.44,0.74,100,"Moderate",13.6,20.4,17.2,14.8,"01-Sep-1994","1% within 1 year","CRISIL Hybrid 50+50 Index","Nifty 50 Hybrid 50:50 Index","India's largest hybrid fund with 30-year track record.","Conservative equity investors.","Dynamic equity-debt allocation for wealth creation.","Gopal Agrawal","Senior Fund Manager","20+ years hybrid fund management."));
        funds.add(f("KOTAK_BAF","Kotak Balanced Advantage - Direct","Kotak Mahindra MF","Hybrid","Balanced Advantage",19.34,18234,0.53,0.53,500,"Moderate",11.8,15.4,13.8,12.1,"01-Aug-2021","1% within 1 year","CRISIL Hybrid 50+50 Index","Nifty 50 Hybrid 50:50 Index","Systematic dynamic asset allocation with low volatility.","Conservative investors wanting equity-like returns with less risk.","Capital appreciation with downside protection through dynamic allocation.","Abhishek Bisen","Head of Fixed Income","20+ years in fixed income and hybrid funds."));
        funds.add(f("DSP_BAF","DSP Dynamic Asset Allocation - Direct","DSP Mutual Fund","Hybrid","Balanced Advantage",21.34,8234,0.72,0.72,500,"Moderate",10.9,14.2,12.8,11.4,"21-Feb-2014","1% within 1 year","CRISIL Hybrid 50+50 Index","Nifty 50 Hybrid 50:50 Index","Rule-based dynamic allocation using P/BV model.","Investors seeking automated market-level rebalancing.","Optimal returns through model-driven equity-debt allocation.","Atul Bhole","Fund Manager","15+ years in hybrid fund management."));
        funds.add(f("MIRAE_HYBRID","Mirae Asset Aggressive Hybrid - Direct","Mirae Asset MF","Hybrid","Aggressive Hybrid",28.34,9234,0.42,0.42,1000,"Moderate",14.8,18.9,17.2,15.3,"29-Jul-2015","1% within 1 year","CRISIL Hybrid 35+65 Aggressive","NIFTY 50 Hybrid Composite Debt 65:35","Consistent outperformer in aggressive hybrid category.","Investors with moderate risk appetite and 3-5 year horizon.","Wealth creation through 65-80% equity and 20-35% debt allocation.","Gaurav Kochar","Fund Manager","15+ years experience."));
        funds.add(f("SBI_HYBRID","SBI Equity Hybrid Fund - Direct","SBI Mutual Fund","Hybrid","Aggressive Hybrid",228.34,67234,0.90,0.40,1000,"Moderate",13.4,17.8,15.9,16.2,"09-Oct-1995","1% within 1 year","CRISIL Hybrid 35+65 Aggressive","NIFTY 50 Hybrid Composite Debt 65:35","One of India's oldest hybrid funds with 28-year history.","Conservative investors wanting steady equity+debt returns.","Long-term wealth creation through equity-debt hybrid portfolio.","Dinesh Ahuja","Fund Manager","20+ years in hybrid fund management."));
        funds.add(f("AXIS_HYBRID","Axis Equity Hybrid Fund - Direct","Axis Mutual Fund","Hybrid","Aggressive Hybrid",29.34,8234,0.64,0.64,500,"Moderate",13.8,17.4,15.8,14.2,"09-Aug-2018","1% within 1 year","CRISIL Hybrid 35+65 Aggressive","NIFTY 50 Hybrid Composite Debt 65:35","Quality-focused aggressive hybrid fund from Axis AMC.","Investors wanting quality equity exposure with debt cushion.","Capital appreciation with stability through equity-debt blend.","Jinesh Gopani","Head of Equity","Pioneer of quality investing in India."));
        funds.add(f("EDELWEISS_BAF","Edelweiss Balanced Advantage - Direct","Edelweiss MF","Hybrid","Balanced Advantage",42.34,5234,0.48,0.48,1000,"Moderate",11.4,14.8,13.2,11.8,"20-Aug-2009","1% within 1 year","CRISIL Hybrid 50+50 Index","Nifty 50 Hybrid 50:50 Index","Factor-model driven balanced advantage fund.","Risk-averse investors seeking tax-efficient equity returns.","Capital appreciation with downside protection via dynamic allocation.","Bhavesh Jain","Fund Manager","15+ years in hybrid strategies."));

        // ── DEBT (8) ──────────────────────────────────────────────────────────
        funds.add(f("SUND_SD","Sundaram Short Duration - Direct","Sundaram MF","Debt","Short Duration",29.83,1876,0.60,0.28,500,"Low",7.4,6.8,7.1,8.2,"20-Mar-2004","Nil","Nifty Short Duration Debt Index","CRISIL Short Term Bond Fund Index","Short-duration debt for stable returns with low credit risk.","Conservative investors with 1-3 year horizon.","Stable returns through short-duration high-quality debt.","Sandeep Agarwal","Head - Fixed Income","18+ years in fixed income."));
        funds.add(f("HDFC_CORP","HDFC Corporate Bond - Direct","HDFC Mutual Fund","Debt","Corporate Bond",29.14,28745,0.56,0.28,100,"Low",7.8,7.2,7.6,8.4,"29-Jun-2010","Nil","Nifty Corporate Bond Index","CRISIL Corporate Bond Composite","India's largest corporate bond fund.","Investors wanting better than FD returns with safety.","Income generation through AAA/AA+ corporate bonds.","Anupam Joshi","Fund Manager","CFA with 15+ years fixed income experience."));
        funds.add(f("ICICI_BOND","ICICI Pru Bond Fund - Direct","ICICI Prudential MF","Debt","Medium to Long Duration",39.23,8234,0.99,0.49,1000,"Moderate",8.4,7.8,8.2,9.1,"20-Jan-2010","Nil","CRISIL Composite Bond Fund Index","Nifty 10-Year Benchmark G-Sec","Active duration management for capital gains + interest income.","Sophisticated debt investors comfortable with interest rate risk.","Total return through active management of duration and credit.","Manish Banthia","Deputy CIO - Fixed Income","20+ years in debt markets."));
        funds.add(f("AXIS_LIQUID","Axis Liquid Fund - Direct","Axis Mutual Fund","Debt","Liquid",2842.34,42341,0.09,0.09,5000,"Low",7.1,6.8,6.4,7.2,"09-Oct-2009","Nil","CRISIL Liquid Debt Index","Nifty Liquid Index","Safest debt fund with overnight/short-term investments.","Investors parking surplus cash for 1 day to 3 months.","Capital preservation with liquidity through short-term instruments.","Devang Shah","Fund Manager","15+ years in fixed income."));
        funds.add(f("SBI_MAGNUM","SBI Magnum Medium Duration - Direct","SBI Mutual Fund","Debt","Medium Duration",52.34,12234,0.79,0.29,1000,"Moderate",7.9,7.4,7.8,8.6,"12-Nov-2003","Nil","CRISIL Medium Term Debt Index","Nifty Medium Duration Debt Index","Active medium-duration debt fund from India's largest bank AMC.","Conservative investors with 2-4 year debt horizon.","Regular income with capital appreciation through medium-duration bonds.","Dinesh Ahuja","Fund Manager","20+ years in debt markets."));
        funds.add(f("KOTAK_BANK_PSU","Kotak Banking and PSU Debt - Direct","Kotak Mahindra MF","Debt","Banking and PSU",59.34,16234,0.26,0.26,1000,"Low",7.6,7.1,7.4,8.1,"29-Dec-1998","Nil","Nifty Banking and PSU Debt Index","CRISIL Banking and PSU Debt Index","Invests only in bank and PSU bonds - safest debt category.","Ultra-conservative investors wanting safety of bank/PSU bonds.","Capital safety with regular income through bank and PSU bonds.","Abhishek Bisen","Head of Fixed Income","20+ years fixed income experience."));
        funds.add(f("NIPPON_INCOME","Nippon India Income Fund - Direct","Nippon India MF","Debt","Medium to Long Duration",96.34,4234,1.29,0.79,500,"Moderate",8.1,7.6,8.0,9.4,"01-Jan-1998","Nil","CRISIL Composite Bond Fund Index","Nifty 10-Year G-Sec Index","Active income fund with long track record since 1998.","Income-seeking investors comfortable with duration risk.","Regular income with capital appreciation through active debt management.","Vivek Sharma","Fund Manager","18+ years fixed income experience."));
        funds.add(f("DSP_CREDIT","DSP Credit Risk Fund - Direct","DSP Mutual Fund","Debt","Credit Risk",42.34,1234,1.59,1.09,1000,"High",9.2,8.4,8.9,9.8,"13-May-2013","1% if within 12 months","CRISIL Credit Risk Debt Index","Nifty Credit Risk Bond Index","Higher-yield debt through controlled credit risk in AA/A-rated bonds.","Investors wanting fixed-income-plus returns accepting credit risk.","Superior returns through investment in high-yield corporate bonds.","Saurabh Bhatia","Fund Manager","15+ years fixed income experience."));

        // ── INDEX FUNDS (8) ───────────────────────────────────────────────────
        funds.add(f("UTI_NIFTY50","UTI Nifty 50 Index Fund - Direct","UTI Mutual Fund","Index","Nifty 50",165.78,18967,0.25,0.19,500,"Moderate",14.2,17.8,16.4,13.2,"06-Mar-2000","Nil","Nifty 50 TRI","Nifty 50","India's oldest and most trusted Nifty 50 index fund.","Cost-conscious passive investors.","Replicate Nifty 50 performance with minimal tracking error.","Sharwan Kumar Goyal","Fund Manager - Passive","Head of passive strategies at UTI AMC."));
        funds.add(f("MIRAE_MC150","Mirae Asset Midcap 150 ETF FOF","Mirae Asset MF","Index","Midcap 150",23.46,4512,0.16,0.07,500,"High",19.8,24.6,0.0,21.3,"24-Mar-2022","Nil","Nifty Midcap 150 TRI","Nifty Midcap 100 TRI","Ultra-low cost mid-cap index fund.","Cost-conscious mid-cap investors.","Replicate Nifty Midcap 150 at lowest cost.","Ekta Gala","Fund Manager - Passive","Specialist in passive strategies."));
        funds.add(f("SBI_NIFTY","SBI Nifty Index Fund - Direct","SBI Mutual Fund","Index","Nifty 50",196.34,12234,0.17,0.17,5000,"Moderate",14.1,17.6,16.2,13.8,"12-Jan-2002","Nil","Nifty 50 TRI","Nifty 50","Lowest-cost Nifty 50 fund from India's largest AMC.","Retail investors beginning their passive investing journey.","Replicates Nifty 50 with zero active risk.","Raviprakash Sharma","Fund Manager","Dedicated passive fund manager."));
        funds.add(f("HDFC_INDEX","HDFC Index Nifty 50 Plan - Direct","HDFC Mutual Fund","Index","Nifty 50",198.34,15234,0.20,0.20,100,"Moderate",14.0,17.5,16.0,13.6,"17-Jul-2002","Nil","Nifty 50 TRI","Nifty 50","HDFC's passively managed Nifty 50 index fund.","Investors wanting low-cost equity market exposure.","Passive wealth creation by tracking Nifty 50.","Krishan Kumar Daga","Fund Manager","Passive investment specialist."));
        funds.add(f("NIPPON_NIFTY","Nippon India Index Nifty 50 - Direct","Nippon India MF","Index","Nifty 50",34.78,9234,0.20,0.20,100,"Moderate",14.0,17.4,15.9,14.1,"28-Sep-2010","Nil","Nifty 50 TRI","Nifty 50","Nippon's low-cost Nifty 50 tracker with high liquidity.","Index investors wanting daily liquidity.","Track Nifty 50 performance at minimal cost.","Mehul Dama","Fund Manager - Passive","12+ years in passive fund management."));
        funds.add(f("UTI_NIFTY_NEXT","UTI Nifty Next 50 Index - Direct","UTI Mutual Fund","Index","Nifty Next 50",78.34,9234,0.30,0.26,500,"High",16.2,20.4,18.7,14.8,"08-Jun-1998","Nil","Nifty Next 50 TRI","Nifty Next 50","Tracks Nifty Next 50 - tomorrow's Nifty 50 companies.","Investors wanting exposure to high-growth blue-chips of the future.","Long-term wealth creation by tracking Nifty Next 50 index.","Sharwan Kumar Goyal","Fund Manager - Passive","Head of passive strategies at UTI AMC."));
        funds.add(f("ICICI_NIFTY","ICICI Pru Nifty 50 Index - Direct","ICICI Prudential MF","Index","Nifty 50",197.34,14234,0.17,0.17,100,"Moderate",14.1,17.6,16.1,13.7,"26-Feb-2002","Nil","Nifty 50 TRI","Nifty 50","ICICI's consistently low-tracking-error Nifty 50 fund.","Passive investors wanting Nifty 50 exposure.","Replication of Nifty 50 performance.","Nishit Patel","Fund Manager","Passive investment specialist."));
        funds.add(f("DSP_NIFTY","DSP Nifty 50 Index Fund - Direct","DSP Mutual Fund","Index","Nifty 50",21.34,4234,0.18,0.18,500,"Moderate",14.0,17.5,16.0,13.4,"04-Jul-2019","Nil","Nifty 50 TRI","Nifty 50","Newer but highly efficient Nifty 50 tracking fund.","Low-cost passive investors.","Efficient replication of Nifty 50 index.","Anil Ghelani","Head of Passive Investments","Pioneer in India's ETF and passive fund management."));

        // ── INTERNATIONAL (4) ─────────────────────────────────────────────────
        funds.add(f("MOF_NASDAQ","Motilal Oswal Nasdaq 100 FOF","Motilal Oswal MF","International","US Equity",28.64,5678,0.58,0.25,500,"Very High",31.4,14.2,22.6,19.8,"29-Nov-2018","1% within 15 days","Nasdaq 100 TRI (INR)","S&P 500 TRI (INR)","Invest in Apple, Microsoft, NVIDIA, Google via Indian MF route.","Investors wanting US tech exposure from India.","Long-term appreciation through Nasdaq 100 index companies.","Swapnil Mayekar","Fund Manager - International","Specialist in US equity strategies."));
        funds.add(f("EDELWEISS_US","Edelweiss US Technology FOF - Direct","Edelweiss MF","International","US Equity",35.23,2341,0.76,0.46,500,"Very High",28.4,12.8,20.1,18.4,"28-Aug-2020","Nil","S&P 500 Information Technology TRI (INR)","Nasdaq 100 TRI (INR)","Pure US technology sector exposure through global ETFs.","Investors bullish on US tech sector (AI, cloud, semiconductor).","Capital appreciation through US technology sector leaders.","Bhavesh Jain","Fund Manager","15+ years in international equity."));
        funds.add(f("MIRAE_NYSE","Mirae Asset NYSE FANG+ FOF - Direct","Mirae Asset MF","International","US Equity",18.23,1234,0.52,0.52,1000,"Very High",38.2,16.4,0.0,24.8,"14-Jan-2021","Nil","NYSE FANG+ TRI (INR)","Nasdaq 100 TRI (INR)","Concentrated exposure to META, APPLE, AMAZON, NETFLIX, GOOGLE+.","Aggressive investors wanting concentrated FAANG exposure.","Capital appreciation through the world's largest tech companies.","Gaurav Kochar","Fund Manager","15+ years international equity experience."));
        funds.add(f("NIPPON_JAPAN","Nippon India Japan Equity FOF - Direct","Nippon India MF","International","Japan Equity",24.34,982,0.58,0.58,500,"Very High",22.4,8.2,12.4,11.2,"26-Aug-2014","1% within 1 year","TOPIX (INR)","Nikkei 225 (INR)","Diversify into Japan's equity market - world's 3rd largest economy.","Investors wanting geographic diversification beyond India and US.","Long-term capital growth through Japanese equity markets.","Sanjay Parekh","Fund Manager","18+ years in international fund management."));

        // ── SECTORAL (10) ─────────────────────────────────────────────────────
        funds.add(f("MIRAE_BFSI","Mirae Asset Banking & Financial Services","Mirae Asset MF","Sectoral","Banking and Financial Services",32.84,2134,1.69,0.51,500,"Very High",12.8,19.4,16.2,14.6,"15-Jul-2015","1% within 1 year","Nifty Financial Services TRI","Nifty Bank TRI","Pure-play BFSI sector fund - backbone of India's economy.","Investors bullish on Indian banking with 5+ year view.","Capital appreciation through banking and financial services sector.","Gaurav Misra","Senior Fund Manager","15+ years BFSI sector expertise."));
        funds.add(f("TATA_INFRA","Tata Infrastructure Fund - Direct","Tata Mutual Fund","Sectoral","Infrastructure",164.23,3241,1.98,0.98,500,"Very High",45.6,38.4,28.1,16.8,"31-Dec-2004","0.25% within 30 days","Nifty Infrastructure TRI","S&P BSE India Infrastructure TRI","Rides India's Rs.11 lakh crore capex supercycle.","Investors betting on India's infrastructure build-out.","Capital appreciation through infrastructure-related stocks.","Abhinav Sharma","Fund Manager","10+ years sectoral fund management."));
        funds.add(f("ICICI_PHARMA","ICICI Pru Pharma Healthcare - Direct","ICICI Prudential MF","Sectoral","Pharma and Healthcare",318.34,5234,1.28,0.78,5000,"Very High",38.2,26.8,22.4,16.8,"30-Jun-2004","1% within 1 year","Nifty Pharma TRI","S&P BSE Healthcare TRI","Exposure to India's $130 billion pharma and healthcare sector.","Investors bullish on global and domestic healthcare industry.","Long-term capital appreciation through pharma and healthcare companies.","Mrinal Singh","Fund Manager","18+ years in pharma sector research."));
        funds.add(f("SBI_TECH","SBI Technology Opportunities - Direct","SBI Mutual Fund","Sectoral","Technology",192.34,3821,1.01,0.51,500,"Very High",42.8,28.4,26.8,18.4,"09-Jan-2013","0.1% if within 3 days","Nifty IT TRI","S&P BSE IT TRI","Pure IT sector fund riding India's $254 billion IT industry.","Investors bullish on India's IT and digital sector.","Capital appreciation through Indian IT sector leaders.","Saurabh Pant","Fund Manager","16+ years in tech sector research."));
        funds.add(f("TATA_DIGITAL","Tata Digital India Fund - Direct","Tata Mutual Fund","Sectoral","Technology",47.23,3212,0.39,0.39,5000,"Very High",44.2,30.1,28.4,22.1,"28-Dec-2015","0.25% within 30 days","Nifty IT TRI","S&P BSE IT TRI","Comprehensive digital economy fund - IT, fintech, platforms.","Investors wanting Indian digital economy exposure.","Long-term wealth from India's digitalization journey.","Meeta Shetty","Fund Manager","15+ years in digital economy research."));
        funds.add(f("HDFC_DEF","HDFC Defence Fund - Direct","HDFC Mutual Fund","Sectoral","Defence",27.23,6234,0.61,0.61,500,"Very High",56.4,0.0,0.0,48.2,"19-Jun-2023","1% within 1 year","Nifty India Defence TRI","S&P BSE India Defence Index","India's first defence sector fund riding Aatmanirbhar Bharat.","Investors bullish on India's Rs.6 lakh crore defence modernization.","Capital appreciation through India's growing defence industry.","Abhishek Poddar","Fund Manager","16+ years equity research experience."));
        funds.add(f("NIPPON_PHARMA","Nippon India Pharma Fund - Direct","Nippon India MF","Sectoral","Pharma and Healthcare",378.34,7234,1.45,0.95,5000,"Very High",35.6,24.2,20.8,15.4,"01-Jun-2004","1% within 1 year","S&P BSE Healthcare TRI","Nifty Pharma TRI","Veteran pharma fund with 20-year track record.","Long-term pharma sector investors.","Capital appreciation through domestic and global pharma companies.","Sailesh Bhan","Deputy CIO","22+ years in equity markets."));
        funds.add(f("DSP_NATURAL","DSP Natural Resources & New Energy","DSP Mutual Fund","Sectoral","Energy and Resources",72.34,2341,1.48,0.98,500,"Very High",31.8,22.4,18.6,12.8,"25-Apr-2008","1% within 1 year","S&P BSE Metal TRI","S&P BSE Energy TRI","Energy transition fund - oil, gas, metals, green energy.","Investors bullish on commodity and energy super-cycle.","Capital appreciation through natural resources and new energy.","Jay Kothari","VP and International Business Head","15+ years in sectoral investing."));
        funds.add(f("ICICI_BANK","ICICI Pru Banking & Financial - Direct","ICICI Prudential MF","Sectoral","Banking and Financial Services",122.34,8423,1.03,0.53,5000,"Very High",14.8,21.2,17.8,17.4,"22-Aug-2008","1% within 1 year","Nifty Financial Services TRI","Nifty Bank TRI","ICICI's banking sector fund with deep BFSI research backing.","Long-term banking sector bulls.","Capital appreciation through Indian banking and NBFC sector.","Sankaran Naren","CIO","India's most respected fund manager."));
        funds.add(f("UTI_TRANSPORT","UTI Transportation & Logistics","UTI Mutual Fund","Sectoral","Transportation and Logistics",268.34,1821,2.41,1.91,5000,"Very High",47.2,30.4,24.8,14.2,"11-Apr-2004","1% within 1 year","Nifty India Transportation Index","S&P BSE Transportation TRI","Transport sector fund riding India's logistics boom.","Investors bullish on India's transport and logistics growth story.","Capital appreciation through transport, logistics and auto ancillary.","Deepesh Agarwal","Fund Manager","14+ years in equity fund management."));

        // ── MULTI ASSET & OTHERS (6) ──────────────────────────────────────────
        funds.add(f("ICICI_MULTI","ICICI Pru Multi Asset Fund - Direct","ICICI Prudential MF","Multi Asset","Multi Asset Allocation",624.34,26234,1.68,0.98,1000,"Moderate",18.4,22.1,18.9,17.2,"31-Oct-2002","1% within 1 year","60% Nifty 500 + 20% Gold + 20% CRISIL Short Bond","Nifty 500 TRI","Diversified across equity, debt, gold and REITs for all seasons.","Investors wanting one-fund solution across all asset classes.","Optimal risk-adjusted returns through multi-asset diversification.","Sankaran Naren","CIO","India's most respected multi-asset manager."));
        funds.add(f("HDFC_GOLD","HDFC Gold Fund - Direct","HDFC Mutual Fund","Commodity","Gold",26.34,4234,0.49,0.49,500,"High",16.2,12.8,14.4,8.4,"01-Nov-2011","Nil","Domestic Gold Price","MCX Gold","Invest in digital gold through SBI Gold ETF without demat account.","Investors wanting gold exposure through SIP route.","Protect wealth against inflation through gold investments.","Krishan Kumar Daga","Fund Manager","Commodity investment specialist."));
        funds.add(f("AXIS_GOLD","Axis Gold Fund - Direct","Axis Mutual Fund","Commodity","Gold",19.23,1234,0.18,0.18,100,"High",16.1,12.7,14.2,9.1,"20-Oct-2011","Nil","Domestic Gold Price","MCX Gold","Lowest-cost gold fund of funds with high purity exposure.","Investors hedging portfolio with gold through SIP.","Preserve wealth and hedge inflation through gold.","Devang Shah","Fund Manager","Fixed income and commodity specialist."));
        funds.add(f("SBI_CONTRA","SBI Contra Fund - Direct","SBI Mutual Fund","Equity","Contra",346.34,18234,0.84,0.84,500,"High",28.4,32.8,29.4,19.8,"14-Jul-1999","1% within 1 year","S&P BSE 500 TRI","Nifty 500 TRI","Contrarian strategy - buys beaten-down value stocks.","Aggressive investors with 5+ year horizon wanting contrarian alpha.","Capital appreciation through contrarian value investing.","Dinesh Balachandran","Fund Manager","Specialist in contrarian and value investing."));
        funds.add(f("NIPPON_VALUE","Nippon India Value Fund - Direct","Nippon India MF","Equity","Value",169.34,8234,0.97,0.97,500,"High",22.8,26.4,24.8,17.8,"08-Jun-2005","1% within 1 year","S&P BSE 500 TRI","Nifty 500 TRI","Value-oriented fund buying quality companies at discount to intrinsic value.","Patient investors with 5-7 year horizon preferring value approach.","Long-term wealth through value investing in undervalued companies.","Meenakshi Dawar","Fund Manager","17+ years in value investing."));
        funds.add(f("HDFC_FOCUSED","HDFC Focused 30 Fund - Direct","HDFC Mutual Fund","Equity","Focused",162.34,7823,0.89,0.89,500,"High",21.4,25.6,23.2,18.9,"17-Sep-2004","1% within 1 year","Nifty 500 TRI","S&P BSE 500 TRI","High-conviction 30-stock concentrated portfolio.","Investors wanting manager's best ideas without diversification dilution.","Superior long-term alpha through a concentrated best-idea portfolio.","Roshi Jain","Fund Manager","25+ years - India's most experienced fund manager."));

        int added = 0;
        for (Fund fund : funds) {
            if (!fundRepo.existsById(fund.getId())) {
                fundRepo.save(fund);
                added++;
            }
        }
        log.info("Funds seeded: " + added + " new funds added. Total in DB: " + fundRepo.count());
    }
}
